name: Haskell Cabal

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        include:
          - ghc-version: '8.8.4'
            cabal-version: '3.0.0.0'
          - ghc-version: '8.6.5'
            cabal-version: '2.4.0.0'
          - ghc-version: '8.4.4'
            cabal-version: '2.2.0.0'


    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-haskell@v1
      with:
        ghc-version: ${{ matrix.ghc-version }}
        cabal-version: ${{ matrix.cabal-version }}

    - name: Cache
      uses: actions/cache@v1
      env:
        cache-name: cache-cabal
      with:
        path: ~/.cabal
        key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/*.cabal') }}-${{ hashFiles('**/cabal.project') }}
        restore-keys: |
          ${{ runner.os }}-build-${{ env.cache-name }}-
          ${{ runner.os }}-build-
          ${{ runner.os }}-

    - name: Install dependencies
      run: |
        set -x
        cabal new-update
        cabal new-build --only-dependencies --enable-tests --enable-benchmarks all
    - name: Build
      run: |
        set -x
        cabal new-build --enable-tests --enable-benchmarks all
    - name: Run tests
      run: |
        set -x
        cabal new-test all

### Local Variables: ***
### mode:yaml ***
### indent-tabs-mode: nil ***
### End: ***
